title: Page

pages: false

options:
  preview: true
  template: false
  status: true
  url: true
  delete: true

fields:
  title:
    label: Title
    type:  text

  text:
    label: Text
    type:  textarea
